### ISSUE TITLE
meshes with subdomains

### ISSUE THREAD

**Issue by nschloe** [wildmeshing/fTetWild#43]
I'm wondering if I can make fTetWild work for domains which have separate subdomains in them, e.g., a ball in a box. If I understand correctly, fTetWild's _union_ operation dissolves subdomain boundaries. I need to have that boundary (approximately) preserved though, and also need to be able to recover the subdomain tet meshes. The mesh should be conformant across the boundaries.

**Comment by Yixin-Hu** [comment]
Hi, you don't need to use Boolean operations in this case. For example, if you have a box that contains a ball inside, simply let the face normal of the two mesh both point out (so that the volume of the ball is not carved inside the box). The output would be a tetmesh of the box with the boundary of the ball preserved inside. 

I don't get the meaning of "dissolve".

**Comment by nschloe** [comment]
Thanks for the quick reply. It answers my question fully.

By "dissolve", I meant the disappearance of the interface boundary, e.g., in this composed mesh with the circle on the left:

![screenshot](https://user-images.githubusercontent.com/181628/146244449-08cb9f4d-54dc-4a16-b2a6-342759fa4da7.png)

(Generated with [pygmsh](https://github.com/nschloe/pygmsh).)

I think I'll just start playing around with fTetWild!
