### ISSUE TITLE
Triangulating a 3d polygon

### ISSUE THREAD

**Issue by benstadin** [wildmeshing/fTetWild#61]
I have a flat 3d polygon (geojson polygon) as input data most of the time and a 3d point cloud other times.

Do I need to prepare the input data in some way, or is this library able to triangulate the input data directly?

**Comment by Yixin-Hu** [comment]
Hi,

fTetWild only takes triangle mesh as input. It works on 3d triangulated polygons. But since the flat polygon does not have volume, the output may not meet your expectation. Maybe try to model the polygon to make it a facet of a polyhedron. 

For 3d point cloud, you can simply use Delaunay tetrahedralization to preserve the points.
