### ISSUE TITLE
error: could not find git for clone of libigl-download

### ISSUE THREAD

**Issue by ChristopherVoltl** [wildmeshing/fTetWild#9]
Hello,

I'm getting an error when compiling with regards to the libigl library 

```
`CMake Error at C:/cpp/cmake-3.18.0-rc2-win32-x86/cmake-3.18.0-rc2-win32-x86/share/cmake-3.18/Modules/ExternalProject.cmake:2346 (message):
  error: could not find git for clone of libigl-download
Call Stack (most recent call first):
  C:/cpp/cmake-3.18.0-rc2-win32-x86/cmake-3.18.0-rc2-win32-x86/share/cmake-3.18/Modules/ExternalProject.cmake:3224 (_ep_add_download_command)
  CMakeLists.txt:9 (ExternalProject_Add)


CMake Error at cmake/DownloadProject.cmake:171 (message):
  CMake step for libigl failed: 1
Call Stack (most recent call first):
  cmake/FloatTetwildDownloadExternal.cmake:15 (download_project)
  cmake/FloatTetwildDownloadExternal.cmake:29 (float_tetwild_download_project)
  cmake/FloatTetwildDependencies.cmake:44 (float_tetwild_download_libigl)
  CMakeLists.txt:82 (include)`
```

I am running on windows 10 and using visual studio 2019 command prompt to execute the commands.  
Is there something I am doing wrong in regards to the installation with cmake?

Thank you,
Christopher

**Comment by teseoch** [comment]
Dear Christopher,

this is probably because you don't have the `git` command available in your path.

You can try this by opening a cmd and typing `git --version`. If it tells you something like
> no such command
then you need to add git to your path.

Google for the name of the git client you are using to locate where the `git.exe` file is.
Once you find it, add it to the `PATH` environment variable, close the cmd and try again `git --version`, it should give you the git version.

Close and reopen the cmake gui and try again, it should wrok

**Comment by ChristopherVoltl** [comment]
That solved it thanks
